"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { ensureProfile, normalizeUsername, supabase } from "@/lib/supabase";
import type { Friendship, Profile } from "@/lib/types";

export default function FriendsPage(){
  const [user,setUser]=useState<User|null|undefined>(undefined); const [rows,setRows]=useState<Friendship[]>([]); const [profiles,setProfiles]=useState<Profile[]>([]); const [username,setUsername]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function load(){const db=supabase();const {data:userData}=await db.auth.getUser(); if(!userData.user){setUser(null);return;} await ensureProfile(userData.user); setUser(userData.user); const {data:f}=await db.from("friendships").select("*").order("created_at",{ascending:false}); const friendships=(f??[]) as Friendship[]; setRows(friendships); const ids=Array.from(new Set(friendships.flatMap((row)=>[row.requester_id,row.addressee_id]))); if(!ids.length){setProfiles([]);return;} const {data:p}=await db.from("profiles").select("user_id,display_name,username").in("user_id",ids);setProfiles((p??[]) as Profile[])}
  useEffect(()=>{void load()},[]);
  const byId=useMemo(()=>Object.fromEntries(profiles.map((p)=>[p.user_id,p])),[profiles]);
  if(user===undefined)return <div className="empty">Loading friends…</div>;
  if(!user)return <div className="empty"><strong>Sign in to use friends</strong><span>Add players by their unique ManaPair username.</span><div className="empty-action"><a className="primary" href="/login">Sign in</a></div></div>;
  const incoming=rows.filter((r)=>r.status==="pending"&&r.addressee_id===user.id); const outgoing=rows.filter((r)=>r.status==="pending"&&r.requester_id===user.id); const friends=rows.filter((r)=>r.status==="accepted");
  async function send(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const clean=normalizeUsername(username);const db=supabase();const {data:target,error:findErr}=await db.from("profiles").select("user_id,display_name,username").eq("username",clean).maybeSingle();if(findErr||!target){setMessage("No player found with that username.");setBusy(false);return;}if(target.user_id===user.id){setMessage("You can’t add yourself.");setBusy(false);return;}const {error}=await db.from("friendships").insert({requester_id:user.id,addressee_id:target.user_id});setBusy(false);if(error){setMessage(error.code==="23505"?"You already have a friend request or friendship with this player.":error.message);return;}setUsername("");setMessage(`Friend request sent to @${target.username}.`);await load()}
  async function accept(id:string){setBusy(true);const {error}=await supabase().from("friendships").update({status:"accepted",updated_at:new Date().toISOString()}).eq("id",id);setBusy(false);if(error)setMessage(error.message);else await load()}
  async function remove(id:string){setBusy(true);const {error}=await supabase().from("friendships").delete().eq("id",id);setBusy(false);if(error)setMessage(error.message);else await load()}
  const other=(row:Friendship)=>byId[row.requester_id===user.id?row.addressee_id:row.requester_id];
  return <><div className="page-head"><div><p className="eyebrow">Social</p><h1>Friends</h1></div><p className="muted">Find players by username. Usernames are unique across ManaPair.</p></div>
  <div className="split friends-layout"><div className="grid">
    <section className="panel"><h2>Your friends</h2>{friends.length===0?<div className="empty compact"><strong>No friends yet</strong><span>Add someone by username.</span></div>:friends.map((row)=>{const p=other(row);return <div className="history-row" key={row.id}><Link href={`/players/${p?.user_id}`}><strong>{p?.display_name||"Player"}</strong><div className="tiny">@{p?.username||"player"}</div></Link><button className="quiet-button" disabled={busy} onClick={()=>void remove(row.id)}>Remove</button></div>})}</section>
    {incoming.length?<section className="panel"><h2>Requests</h2>{incoming.map((row)=>{const p=byId[row.requester_id];return <div className="history-row" key={row.id}><div><strong>{p?.display_name||"Player"}</strong><div className="tiny">@{p?.username||"player"}</div></div><div className="actions"><button className="secondary" disabled={busy} onClick={()=>void accept(row.id)}>Accept</button><button className="quiet-button" disabled={busy} onClick={()=>void remove(row.id)}>Decline</button></div></div>})}</section>:null}
    {outgoing.length?<section className="panel"><h2>Sent requests</h2>{outgoing.map((row)=>{const p=byId[row.addressee_id];return <div className="history-row" key={row.id}><div><strong>{p?.display_name||"Player"}</strong><div className="tiny">@{p?.username||"player"}</div></div><button className="quiet-button" disabled={busy} onClick={()=>void remove(row.id)}>Cancel</button></div>})}</section>:null}
  </div><aside className="panel registration-box"><p className="eyebrow">Add friend</p><h2>Find by username</h2><form className="form" onSubmit={send}><label>Username<input value={username} onChange={(e)=>setUsername(normalizeUsername(e.target.value))} placeholder="player_name" required/></label><button className="primary" disabled={busy||username.length<3}>Send request</button>{message?<div className="message">{message}</div>:null}</form></aside></div></>;
}
