"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { isGeneratedUsername, normalizeIsraeliPhone, normalizeUsername, supabase, validIsraeliMobilePhone, validUsername } from "@/lib/supabase";
import { fmtDate } from "@/lib/date";
import type { Profile, Standing, Tournament } from "@/lib/types";

type Overall={user_id:string;display_name:string;played:number;wins:number;draws:number;losses:number;win_rate:number};
type Contact={phone:string|null};
export function PlayerProfile({playerId,editable=false}:{playerId:string;editable?:boolean}){
 const [profile,setProfile]=useState<Profile|null>(null);const [overall,setOverall]=useState<Overall|null>(null);const [rows,setRows]=useState<Standing[]>([]);const [events,setEvents]=useState<Tournament[]>([]);const [name,setName]=useState("");const [username,setUsername]=useState("");const [phone,setPhone]=useState("");const [message,setMessage]=useState("");
 async function load(){const db=supabase();const contactQuery=editable?db.from("user_contacts").select("phone").eq("user_id",playerId).maybeSingle():Promise.resolve({data:null});const [{data:p},{data:o},{data:s},{data:t},{data:c}]=await Promise.all([db.from("profiles").select("user_id,display_name,username").eq("user_id",playerId).maybeSingle(),db.from("player_overall_stats").select("*").eq("user_id",playerId).maybeSingle(),db.from("tournament_standings").select("*").eq("user_id",playerId),db.from("tournaments").select("*").eq("status","completed").order("ends_at",{ascending:false}),contactQuery]);setProfile(p as Profile|null);setOverall(o as Overall|null);setRows((s??[]) as Standing[]);setEvents((t??[]) as Tournament[]);setName((p as Profile|null)?.display_name??"");setUsername((p as Profile|null)?.username??"");setPhone(normalizeIsraeliPhone((c as Contact|null)?.phone??""))}
 useEffect(()=>{void load()},[playerId]); const history=useMemo(()=>rows.map((r)=>({standing:r,event:events.find((e)=>e.id===r.tournament_id)})).filter((x)=>x.event),[rows,events]);
 async function save(){if(!editable||name.trim().length<2)return;const clean=normalizeUsername(username);const cleanPhone=normalizeIsraeliPhone(phone);if(!validUsername(clean)){setMessage("Username must be 3–24 characters using lowercase letters, numbers or _.");return;}if(!validIsraeliMobilePhone(cleanPhone)){setMessage("Phone number must be a 10-digit Israeli mobile number starting with 05.");return;}const db=supabase();const {error}=await db.from("profiles").update({display_name:name.trim(),username:clean,updated_at:new Date().toISOString()}).eq("user_id",playerId);if(error){setMessage(error.code==="23505"?"That username is already taken.":error.message);return;}const {error:phoneError}=await db.from("user_contacts").update({phone:cleanPhone}).eq("user_id",playerId);if(phoneError){setMessage(phoneError.message);return;}setMessage("Profile and matchup contact number updated.");await load()}
 if(!profile)return <div className="empty">Loading player…</div>;
 return <><div className="profile-head"><div><p className="eyebrow">Player profile</p><h1>{profile.display_name}</h1>{!isGeneratedUsername(profile.username)?<p className="profile-username">@{profile.username}</p>:null}</div>{editable?<Link className="secondary" href="/friends">Friends</Link>:null}</div><div className="stats"><div className="stat"><small>Matches</small><strong>{overall?.played??0}</strong></div><div className="stat"><small>Wins</small><strong>{overall?.wins??0}</strong></div><div className="stat"><small>Losses</small><strong>{overall?.losses??0}</strong></div><div className="stat"><small>Win rate</small><strong>{overall?.win_rate??0}%</strong></div></div>
 {editable?<section className="panel profile-edit"><h2>Profile & contact</h2><div className="form-row"><label>Display name<input value={name} maxLength={32} onChange={(e)=>setName(e.target.value)}/></label><label>Username<input value={username} maxLength={24} onChange={(e)=>setUsername(normalizeUsername(e.target.value))}/><span className="hint">Used for friend requests and admin lookup.</span></label></div><label>Israeli mobile number<input type="tel" inputMode="numeric" autoComplete="tel" maxLength={10} value={phone} onChange={(e)=>setPhone(normalizeIsraeliPhone(e.target.value))} placeholder="0501234567"/><span className="hint">Required to enter tournaments. It must start with 05 and contain exactly 10 digits. It is visible only to players you are paired against in active tournaments.</span></label><div className="actions"><button className="secondary" onClick={save}>Save profile</button></div>{message?<p className="tiny profile-message">{message}</p>:null}</section>:null}
 <section className="panel"><h2>Tournament history</h2>{history.length===0?<div className="empty compact"><strong>No completed tournaments yet</strong><span>Past results and public decklists will appear here.</span></div>:history.map(({standing,event})=><Link className="history-row" key={standing.tournament_id} href={`/tournaments/${standing.tournament_id}`}><div><strong>{event!.name}</strong><div className="tiny">{event!.format} · ended {fmtDate(event!.ends_at)}</div></div><div className="history-score"><strong>{standing.points} pts</strong><div className="tiny">{standing.wins}-{standing.draws}-{standing.losses} · {standing.win_rate}%</div></div></Link>)}</section></>;
}
