"use client";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import type { User } from "@supabase/supabase-js";
import { ensureProfile, normalizeUsername, supabase, validIsraeliMobilePhone } from "@/lib/supabase";
import { parseDecklist } from "@/lib/decklist";
import { fmtDate, fmtDateTime } from "@/lib/date";
import type { DeckCard, Decklist, MatchRow, Profile, Standing, Tournament, UserDeck } from "@/lib/types";

type PlayerJoin = { user_id:string; decklist_id:string|null; profiles:{display_name:string;username:string}|{display_name:string;username:string}[]|null };
type AdminJoin = { user_id:string; profiles:{display_name:string;username:string}|{display_name:string;username:string}[]|null };
type Dispute = { id:string; match_id:string; raised_by:string; reason:string|null; status:string };
type DeckWithCards = Decklist & { decklist_cards: DeckCard[] };
type SavedDeck = UserDeck & { user_deck_cards: DeckCard[] };
type ValidCard = { id:string; oracle_id?:string; name:string };
type Contact = { phone:string|null };

function relProfile(value:PlayerJoin["profiles"]|AdminJoin["profiles"]){if(!value)return {display_name:"Player",username:"player"};return Array.isArray(value)?value[0]??{display_name:"Player",username:"player"}:value}
function maxRoundCount(players:number){if(players<2)return 0;return players%2===0?players-1:players}
function recommendedRoundCount(players:number){if(players<2)return 0;return Math.min(maxRoundCount(players),Math.max(1,Math.ceil(Math.log2(players))))}
function roundOptions(players:number){const recommended=recommendedRoundCount(players);const max=maxRoundCount(players);if(!recommended||!max)return [];return Array.from(new Set([recommended-2,recommended-1,recommended,recommended+1].filter((rounds)=>rounds>=1&&rounds<=max))).sort((a,b)=>a-b)}
function savedCardCount(deck:SavedDeck,section:"main"|"sideboard"){return deck.user_deck_cards.filter((card)=>card.section===section).reduce((sum,card)=>sum+card.quantity,0)}

export default function TournamentPage(){
 const params=useParams<{id:string}>(); const id=params.id;
 const [event,setEvent]=useState<Tournament|null>(null); const [user,setUser]=useState<User|null>(null); const [players,setPlayers]=useState<PlayerJoin[]>([]); const [admins,setAdmins]=useState<AdminJoin[]>([]); const [matches,setMatches]=useState<MatchRow[]>([]); const [standings,setStandings]=useState<Standing[]>([]); const [profiles,setProfiles]=useState<Profile[]>([]); const [disputes,setDisputes]=useState<Dispute[]>([]); const [decklists,setDecklists]=useState<DeckWithCards[]>([]); const [savedDecks,setSavedDecks]=useState<SavedDeck[]>([]); const [hasPhone,setHasPhone]=useState(false); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [deckText,setDeckText]=useState(""); const [deckName,setDeckName]=useState(""); const [deckSource,setDeckSource]=useState(""); const [adminUsername,setAdminUsername]=useState(""); const [selectedRounds,setSelectedRounds]=useState(0);
 const isOwner=Boolean(user&&event&&event.created_by===user.id); const isAdmin=Boolean(user&&event&&(isOwner||admins.some((a)=>a.user_id===user.id))); const joined=Boolean(user&&players.some((p)=>p.user_id===user.id)); const names=useMemo(()=>Object.fromEntries(profiles.map((p)=>[p.user_id,p.display_name])),[profiles]);
 const choices=useMemo(()=>roundOptions(players.length),[players.length]); const recommendedRounds=recommendedRoundCount(players.length);
 const savedDeckChoices=useMemo(()=>savedDecks.slice().sort((a,b)=>a.name.localeCompare(b.name)),[savedDecks]);
 const selectedSavedDeck=deckSource&&deckSource!=="new"?savedDecks.find((deck)=>deck.id===deckSource)??null:null;
 useEffect(()=>{if(!choices.length){setSelectedRounds(0);return}setSelectedRounds((current)=>choices.includes(current)?current:(choices.includes(recommendedRounds)?recommendedRounds:choices[0]))},[choices,recommendedRounds]);

 async function load(){const db=supabase(); const {data:userData}=await db.auth.getUser(); if(userData.user)await ensureProfile(userData.user); setUser(userData.user??null);
   const [{data:t},{data:p},{data:a},{data:m},{data:s},{data:allProfiles},{data:d},{data:dl},{data:sd},{data:contact}]=await Promise.all([
    db.from("tournaments").select("*").eq("id",id).single(),
    db.from("tournament_players").select("user_id,decklist_id,profiles(display_name,username)").eq("tournament_id",id),
    db.from("tournament_admins").select("user_id,profiles(display_name,username)").eq("tournament_id",id),
    db.from("tournament_matches").select("id,tournament_id,player_a,player_b,round_number,player_a_wins,player_b_wins,status,reported_by").eq("tournament_id",id).order("round_number",{ascending:true}).order("created_at",{ascending:true}),
    db.from("tournament_standings").select("*").eq("tournament_id",id).order("points",{ascending:false}).order("game_wins",{ascending:false}),
    db.from("profiles").select("user_id,display_name,username"),
    userData.user?db.from("match_disputes").select("id,match_id,raised_by,reason,status").eq("status","open"):Promise.resolve({data:[]}),
    db.from("decklists").select("id,tournament_id,user_id,name,submitted_at,decklist_cards(card_name,scryfall_id,oracle_id,quantity,section)").eq("tournament_id",id),
    userData.user?db.from("user_decks").select("id,user_id,name,format,created_at,updated_at,user_deck_cards(card_name,scryfall_id,oracle_id,quantity,section)").eq("user_id",userData.user.id).order("updated_at",{ascending:false}):Promise.resolve({data:[]}),
    userData.user?db.from("user_contacts").select("phone").eq("user_id",userData.user.id).maybeSingle():Promise.resolve({data:null})
   ]);
   const tournament=t as Tournament; const library=(sd??[]) as unknown as SavedDeck[]; const currentContact=contact as Contact|null;
   setEvent(tournament); setPlayers((p??[]) as unknown as PlayerJoin[]); setAdmins((a??[]) as unknown as AdminJoin[]); setMatches((m??[]) as MatchRow[]); setStandings((s??[]) as Standing[]); setProfiles((allProfiles??[]) as Profile[]); setDisputes((d??[]) as Dispute[]); setDecklists((dl??[]) as unknown as DeckWithCards[]); setSavedDecks(library); setHasPhone(Boolean(currentContact?.phone&&validIsraeliMobilePhone(currentContact.phone)));
   setDeckSource((current)=>{if(current==="new"||library.some((deck)=>deck.id===current))return current;return library[0]?.id??"new"});
 }
 useEffect(()=>{void load()},[id]);

 async function register(){if(!user)return location.href="/login"; if(!hasPhone){setMessage("Add a valid Israeli mobile number in Profile before registering. It will be visible only to players you are paired against in active tournaments.");return} setBusy(true);setMessage(""); try{
   const db=supabase();
   if(deckSource&&deckSource!=="new"){
     const selected=savedDecks.find((deck)=>deck.id===deckSource); if(!selected)throw new Error("Saved deck not found. Refresh and try again.");
     const {error}=await db.rpc("register_with_saved_deck",{p_tournament_id:id,p_user_deck_id:selected.id}); if(error)throw error;
     setMessage(`Registered with ${selected.name}. ManaPair stored a tournament snapshot, so later library edits will not change this entry.`); await load(); return;
   }
   const parsed=parseDecklist(deckText); const response=await fetch("/api/cards/validate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({names:parsed.map((c)=>c.name)})}); const validated=await response.json() as {cards?:ValidCard[];notFound?:string[];error?:string};
   if(!response.ok||validated.error)throw new Error(validated.error||"Could not validate decklist."); if(validated.notFound?.length)throw new Error(`Unknown card${validated.notFound.length>1?"s":""}: ${validated.notFound.join(", ")}`);
   const byName=new Map((validated.cards??[]).map((c)=>[c.name.toLowerCase(),c])); const {data:deck,error:deckErr}=await db.from("decklists").insert({tournament_id:id,user_id:user.id,name:deckName.trim()||null}).select("id").single(); if(deckErr)throw deckErr;
   const cardRows=parsed.map((entry)=>{const card=byName.get(entry.name.toLowerCase()); return {decklist_id:deck.id,card_name:card?.name||entry.name,scryfall_id:card?.id||null,oracle_id:card?.oracle_id||null,quantity:entry.quantity,section:entry.section}});
   const {error:cardsErr}=await db.from("decklist_cards").insert(cardRows); if(cardsErr){await db.from("decklists").delete().eq("id",deck.id);throw cardsErr;}
   const {error:joinErr}=await db.from("tournament_players").insert({tournament_id:id,user_id:user.id,decklist_id:deck.id}); if(joinErr){await db.from("decklists").delete().eq("id",deck.id);throw joinErr;}
   setDeckText("");setDeckName("");setMessage("Registered. Your decklist stays private until the tournament is completed.");await load();
 }catch(error){setMessage(error instanceof Error?error.message:"Registration failed.")}finally{setBusy(false)}}

 async function start(){if(!selectedRounds)return;setBusy(true);setMessage("");const {data,error}=await supabase().rpc("start_tournament",{p_tournament_id:id,p_rounds:selectedRounds});setBusy(false);if(error){setMessage(error.message);return}setMessage(`${selectedRounds} rounds generated · ${data??"Pairings ready"} total matches.`);await load()}
 async function finish(){if(!confirm("Finish this tournament? Decklists will become public in tournament history."))return;setBusy(true);const {error}=await supabase().rpc("finish_tournament",{p_tournament_id:id});setBusy(false);if(error)setMessage(error.message);else await load()}
 async function cancel(){if(!confirm("Cancel this tournament? Results will stop counting toward player records and private decklists will stay private."))return;setBusy(true);const {error}=await supabase().rpc("cancel_tournament",{p_tournament_id:id});setBusy(false);if(error)setMessage(error.message);else{setMessage("Tournament cancelled.");await load()}}
 async function saveScore(match:MatchRow,a:number,b:number){if(!user)return;setBusy(true);setMessage("");const {error}=await supabase().from("tournament_matches").update({player_a_wins:a,player_b_wins:b,status:"reported",reported_by:user.id,updated_at:new Date().toISOString()}).eq("id",match.id);if(error)setMessage(error.message);else{if(isAdmin)await supabase().from("match_disputes").update({status:"resolved",resolved_at:new Date().toISOString(),resolved_by:user.id}).eq("match_id",match.id).eq("status","open");await load()}setBusy(false)}
 async function dispute(matchId:string){if(!user)return;const reason=prompt("What is wrong with this score? (optional)")??"";const {error}=await supabase().from("match_disputes").insert({match_id:matchId,raised_by:user.id,reason:reason.trim()||null});if(error)setMessage(error.message);else{setMessage("The tournament admins have been notified.");await load()}}
 async function addAdmin(){if(!user||!isOwner)return;const username=normalizeUsername(adminUsername);setBusy(true);setMessage("");const db=supabase();const {data:target,error:findError}=await db.from("profiles").select("user_id,display_name,username").eq("username",username).maybeSingle();if(findError||!target){setMessage("No player found with that username.");setBusy(false);return}if(target.user_id===user.id){setMessage("You are already the tournament owner.");setBusy(false);return}const {error}=await db.from("tournament_admins").insert({tournament_id:id,user_id:target.user_id,added_by:user.id});setBusy(false);if(error){setMessage(error.code==="23505"?"That player is already an admin.":error.message);return}setAdminUsername("");setMessage(`@${target.username} is now a tournament admin.`);await load()}
 async function removeAdmin(userId:string){if(!isOwner)return;setBusy(true);const {error}=await supabase().from("tournament_admins").delete().eq("tournament_id",id).eq("user_id",userId);setBusy(false);if(error)setMessage(error.message);else await load()}

 if(!event)return <div className="empty">Loading tournament…</div>;
 const myMatches=user?matches.filter((m)=>m.player_a===user.id||m.player_b===user.id):[]; const shownMatches=(isAdmin?matches:myMatches).slice().sort((a,b)=>(a.round_number??1)-(b.round_number??1)); const showStandings=event.status==="active"||event.status==="completed"; const activeRounds=event.round_count??(matches.length?Math.max(...matches.map((m)=>m.round_number??1)):0); const roundsToShow=Array.from({length:activeRounds},(_,index)=>index+1); const roundsStat=event.status==="registration"?(isAdmin&&selectedRounds?selectedRounds:"TBD"):(activeRounds||"—");
 return <>
  <div className="page-head"><div><div className="meta"><span className="pill">{event.format}</span><span className="pill">{event.mode==="async"?"Async league":"Scheduled"}</span><span className={`pill status status-${event.status}`}>{event.status}</span></div><h1 className="event-title">{event.name}</h1></div>{isAdmin?<div className="actions">{event.status==="active"?<button className="secondary" disabled={busy} onClick={finish}>Finish tournament</button>:null}{event.status!=="completed"&&event.status!=="cancelled"?<button className="danger" disabled={busy} onClick={cancel}>Cancel tournament</button>:null}</div>:null}</div>
  <div className="stats"><div className="stat"><small>Players</small><strong>{players.length}</strong></div><div className="stat"><small>Rounds</small><strong>{roundsStat}</strong></div><div className="stat"><small>Starts</small><strong className="stat-date">{fmtDate(event.starts_at)}</strong></div><div className="stat"><small>Ends</small><strong className="stat-date">{fmtDate(event.ends_at)}</strong></div></div>
  {event.description?<p className="muted event-description">{event.description}</p>:null}
  {event.status==="cancelled"?<div className="message cancelled-message">This tournament was cancelled. Its results do not count toward player records, and submitted decklists remain private.</div>:null}
  {message?<div className={message.toLowerCase().includes("failed")||message.toLowerCase().includes("unknown")||message.toLowerCase().includes("impossible")||message.toLowerCase().includes("not found")?"message error":"message"}>{message}</div>:null}
  <div className="split tournament-split"><div className="grid">
   <section className="panel"><h2>{showStandings?"Standings":"Players"}</h2>{!showStandings?<div>{players.length===0?<div className="empty compact"><strong>No players yet</strong><span>Share this page so players can register with their decklists.</span></div>:players.map((p)=>{const profile=relProfile(p.profiles);return <div className="history-row" key={p.user_id}><a href={`/players/${p.user_id}`}><strong>{profile.display_name}</strong><div className="tiny">@{profile.username}</div></a><span className="tiny">registered</span></div>})}</div>:<div className="table-wrap"><table><thead><tr><th>#</th><th>Player</th><th>Pts</th><th>W-D-L</th><th>Win rate</th><th>Games</th></tr></thead><tbody>{standings.map((s,i)=><tr key={s.user_id}><td>{i+1}</td><td><a href={`/players/${s.user_id}`}><strong>{s.display_name}</strong></a></td><td><strong>{s.points}</strong></td><td>{s.wins}-{s.draws}-{s.losses}</td><td>{s.win_rate}%</td><td>{s.game_wins}-{s.game_losses}</td></tr>)}</tbody></table></div>}</section>
   {(event.status==="active"||event.status==="completed")&&user?<section className="panel"><h2>{isAdmin?"Rounds, matches & admin controls":"Your rounds"}</h2>{roundsToShow.length===0?<div className="empty compact"><strong>No matches to show</strong></div>:roundsToShow.map((roundNo)=>{const roundMatches=shownMatches.filter((match)=>match.round_number===roundNo);return <div className="grid" key={roundNo}><div className="history-row"><strong>Round {roundNo}</strong><span className="tiny">{isAdmin?`${roundMatches.length} matches`:roundMatches.length?"Paired":"Bye"}</span></div>{roundMatches.length?roundMatches.map((m)=><MatchCard key={m.id} match={m} names={names} userId={user.id} admin={isAdmin} eventStatus={event.status} busy={busy} disputes={disputes} onSave={saveScore} onDispute={dispute}/>):!isAdmin?<div className="empty compact"><strong>Bye</strong><span>No opponent this round.</span></div>:null}</div>})}</section>:null}
   {event.status==="completed"?<Decklists decklists={decklists} names={names}/>:isAdmin&&decklists.length?<section className="panel"><h2>Private decklists</h2><p className="privacy-note"><strong>Admin only:</strong> these stay hidden from other players until the tournament ends.</p><DecklistsInner decklists={decklists} names={names}/></section>:null}
  </div>
  <aside className="grid registration-box">
   <section className="panel"><p className="eyebrow">Event details</p><div className="history-row"><span>Registration closes</span><strong>{fmtDateTime(event.registration_deadline)}</strong></div><div className="history-row"><span>Window</span><strong>{fmtDate(event.starts_at)} – {fmtDate(event.ends_at)}</strong></div><div className="history-row"><span>Mode</span><strong>{event.mode==="async"?"Play anytime":"Scheduled"}</strong></div>{event.round_count?<div className="history-row"><span>Rounds</span><strong>{event.round_count}</strong></div>:null}</section>
   {isAdmin&&event.status==="registration"?<section className="panel"><p className="eyebrow">Pairings</p><h2>Choose number of rounds</h2>{players.length<2?<div className="empty compact"><strong>Waiting for players</strong><span>Round options appear once at least two players are registered.</span></div>:<div className="form"><label>Rounds<select value={selectedRounds} onChange={(e)=>setSelectedRounds(Number(e.target.value))}>{choices.map((rounds)=><option key={rounds} value={rounds}>{rounds} round{rounds===1?"":"s"}{rounds===recommendedRounds?" · Recommended":rounds<recommendedRounds?" · Shorter":" · Extended"}</option>)}</select><span className="hint">Based on {players.length} registered players. ManaPair recommends {recommendedRounds} rounds. Pairings never repeat an opponent.</span></label>{players.length%2===1?<div className="privacy-note">With an odd player count, one player receives a bye in each round.</div>:null}<button className="primary" disabled={busy||!selectedRounds} onClick={()=>void start()}>{busy?"Generating…":`Generate ${selectedRounds} round${selectedRounds===1?"":"s"}`}</button></div>}</section>:null}
   {event.status==="registration"&&!joined?<section className="panel"><h2>Register</h2>{!user?<><p className="muted">Sign in to enter this tournament.</p><a className="primary" href="/login">Sign in</a></>:!hasPhone?<div className="form"><div className="privacy-note"><strong>Add your mobile number before entering.</strong> ManaPair requires a 10-digit Israeli mobile number beginning with 05 so paired players can arrange matches. Your phone number and email are visible only to players you are paired against in active tournaments.</div><a className="primary" href="/profile">Add phone number in Profile</a></div>:<div className="form">
     <label>Deck<select value={deckSource||"new"} onChange={(e)=>setDeckSource(e.target.value)}>{savedDeckChoices.length?<optgroup label="Your saved decks">{savedDeckChoices.map((deck)=><option key={deck.id} value={deck.id}>{deck.name}</option>)}</optgroup>:null}<option value="new">Upload a new decklist</option></select><span className="hint">Choose a deck from your private Decks library, or submit a new tournament-only decklist.</span></label>
     {selectedSavedDeck?<div className="admin-note"><strong>{selectedSavedDeck.name}</strong><div className="tiny">{savedCardCount(selectedSavedDeck,"main")} main{savedCardCount(selectedSavedDeck,"sideboard")?` · ${savedCardCount(selectedSavedDeck,"sideboard")} sideboard`:""}</div><div className="privacy-note">ManaPair will copy this deck into the tournament. Editing or deleting the library version later will not alter your submitted tournament list.</div></div>:<><label>Deck name <span className="hint">optional</span><input value={deckName} onChange={(e)=>setDeckName(e.target.value)} placeholder="Jeskai Control"/></label><label>Decklist<textarea className="decklist-textarea" value={deckText} onChange={(e)=>setDeckText(e.target.value)} placeholder={'4 Lightning Bolt\n4 Counterspell\n...\n\nSideboard:\n2 Dispel\n...'}/><span className="hint">Use “quantity card name”. Card names are validated against Scryfall's complete Magic card catalog.</span></label>{!savedDecks.length?<div className="privacy-note">Want to reuse this deck later? <a href="/decks"><strong>Add decks to your private Decks library.</strong></a></div>:null}</>}
     <div className="privacy-note"><strong>Matchup contact:</strong> by entering, your registered email address and mobile number can be viewed by players you are paired against while the tournament is active. Your decklist remains private until the event ends.</div><button className="primary" disabled={busy||(!selectedSavedDeck&&!deckText.trim())} onClick={register}>{busy?"Registering…":selectedSavedDeck?`Register with ${selectedSavedDeck.name}`:"Submit decklist & register"}</button>
   </div>}</section>:null}
   {joined&&event.status==="registration"?<section className="panel"><h2>You’re registered</h2><p className="muted">Your tournament decklist is locked to this entry and remains private until the tournament is completed.</p></section>:null}
   {(isOwner||admins.length>0)?<section className="panel"><p className="eyebrow">Tournament admins</p><div className="admin-list"><div className="admin-row"><div><strong>{names[event.created_by]||"Owner"}</strong><div className="tiny">Owner</div></div></div>{admins.map((a)=>{const p=relProfile(a.profiles);return <div className="admin-row" key={a.user_id}><div><strong>{p.display_name}</strong><div className="tiny">@{p.username}</div></div>{isOwner?<button className="quiet-button" disabled={busy} onClick={()=>void removeAdmin(a.user_id)}>Remove</button>:null}</div>})}</div>{isOwner?<div className="form admin-add"><label>Add by username<input value={adminUsername} onChange={(e)=>setAdminUsername(normalizeUsername(e.target.value))} placeholder="player_name"/></label><button className="secondary" disabled={busy||adminUsername.length<3} onClick={()=>void addAdmin()}>Add admin</button></div>:null}</section>:null}
  </aside></div>
 </>;
}

function MatchCard({match,names,userId,admin,eventStatus,busy,disputes,onSave,onDispute}:{match:MatchRow;names:Record<string,string>;userId:string;admin:boolean;eventStatus:Tournament["status"];busy:boolean;disputes:Dispute[];onSave:(m:MatchRow,a:number,b:number)=>Promise<void>;onDispute:(id:string)=>Promise<void>}){
 const [a,setA]=useState(match.player_a_wins??0); const [b,setB]=useState(match.player_b_wins??0); const mine=match.player_a===userId||match.player_b===userId; const open=disputes.filter((d)=>d.match_id===match.id); const canEdit=eventStatus!=="cancelled"&&(admin||(eventStatus==="active"&&match.status==="pending"&&mine));
 useEffect(()=>{setA(match.player_a_wins??0);setB(match.player_b_wins??0)},[match.player_a_wins,match.player_b_wins]);
 return <div className="match"><div><div className="match-title">{names[match.player_a]||"Player"} <span className="muted">vs</span> {names[match.player_b]||"Player"}</div>{open.length?<div className="tiny dispute-open">Score disputed{admin?` · ${open.length} open`:""}</div>:<div className="tiny match-state">{match.status==="reported"?"Result reported":"Awaiting result"}</div>}</div><div><div className="score-form"><select className="score-select" value={a} disabled={!canEdit} onChange={(e)=>setA(Number(e.target.value))}>{[0,1,2].map((v)=><option key={v}>{v}</option>)}</select><strong>–</strong><select className="score-select" value={b} disabled={!canEdit} onChange={(e)=>setB(Number(e.target.value))}>{[0,1,2].map((v)=><option key={v}>{v}</option>)}</select>{canEdit?<button className="secondary" disabled={busy} onClick={()=>void onSave(match,a,b)}>{admin&&match.status==="reported"?"Correct":"Report"}</button>:null}</div>{mine&&match.status==="reported"&&!open.some((d)=>d.raised_by===userId)?<button className="dispute" onClick={()=>void onDispute(match.id)}>Score incorrect? Notify admin</button>:null}</div></div>
}
function Decklists({decklists,names}:{decklists:DeckWithCards[];names:Record<string,string>}){return <section className="panel"><h2>Decklists</h2><p className="muted">The tournament is complete, so submitted decklists are now public.</p><DecklistsInner decklists={decklists} names={names}/></section>}
function DecklistsInner({decklists,names}:{decklists:DeckWithCards[];names:Record<string,string>}){if(!decklists.length)return <div className="empty compact">No decklists available.</div>;return <div className="grid grid-2">{decklists.map((d)=><div key={d.id}><h3>{names[d.user_id]||"Player"}{d.name?` · ${d.name}`:""}</h3><div className="deck-preview"><p className="deck-title">Main deck</p>{d.decklist_cards.filter((c)=>c.section==="main").sort((a,b)=>a.card_name.localeCompare(b.card_name)).map((c)=><div className="deck-line" key={`m-${c.card_name}`}><span>{c.quantity} {c.card_name}</span></div>)}{d.decklist_cards.some((c)=>c.section==="sideboard")?<><p className="deck-title">Sideboard</p>{d.decklist_cards.filter((c)=>c.section==="sideboard").sort((a,b)=>a.card_name.localeCompare(b.card_name)).map((c)=><div className="deck-line" key={`s-${c.card_name}`}><span>{c.quantity} {c.card_name}</span></div>)}</>:null}</div></div>)}</div>}
