import Link from "next/link";
import { CURRENT_TERMS_VERSION } from "@/lib/legal";

export default function TermsPage() {
  return <article className="legal-page">
    <p className="eyebrow">Terms of Service</p>
    <h1>Simple rules for a community tool.</h1>
    <p className="legal-updated">Effective version: {CURRENT_TERMS_VERSION}</p>
    <section><h2>1. Acceptance</h2><p>By creating an account or using ManaPair, you agree to these Terms. If you do not agree, do not use the service. We may update these Terms when the service changes; when a material new version is introduced, signed-in users may be asked to accept it before continuing.</p></section>
    <section><h2>2. What ManaPair is</h2><p>ManaPair is a community-run, non-commercial software service for organizing, coordinating, and recording Magic: The Gathering tournaments. It provides tools such as registration, pairings, decklist submission, standings, score reporting, disputes, and tournament history.</p><p>ManaPair is not the organizer, judge, venue, payment processor, prize provider, guarantor, or supervisor of any tournament unless expressly stated otherwise. ManaPair does not collect entry fees or distribute prizes through the service.</p></section>
    <section><h2>3. Community project; no affiliation</h2><p>ManaPair is provided to support the player community and is not operated for profit at this time. ManaPair is not affiliated with, sponsored by, or endorsed by Wizards of the Coast LLC or Hasbro. Magic: The Gathering and related marks belong to their respective owners.</p></section>
    <section><h2>4. Accounts and information</h2><p>You are responsible for keeping your account secure and for providing accurate information, including a usable email address and, when required for tournament participation, a usable Israeli mobile number. You may not impersonate another person, interfere with another user’s account, attempt to bypass access controls, scrape private information, or use ManaPair to harass, threaten, deceive, or abuse other users.</p></section>
    <section><h2>5. Tournament activity and results</h2><p>Tournament creators and appointed admins are responsible for their event rules, eligibility decisions, score corrections, disputes, prizes, schedules, and enforcement. Players are responsible for reporting scores honestly. ManaPair may calculate standings from submitted information, but does not independently verify that a match was played or that a reported result is correct.</p></section>
    <section><h2>6. Matchup contact information</h2><p>To help paired players arrange their match, ManaPair may reveal both the email address and mobile phone number registered to your account only to players you are currently paired against in an active tournament. Your email address and phone number are not part of your public player profile. Pairing-based access ends when the tournament is no longer active.</p><p>You must use an opponent’s email address or phone number only for reasonable tournament coordination. You must not publish it, share it with unrelated people, add it to marketing lists, retain or reuse it for unrelated purposes, or use it for harassment, threats, spam, or other unwanted contact.</p><p>ManaPair validates Israeli mobile numbers by format: the stored number must contain exactly 10 digits and begin with 05. ManaPair does not use SMS verification and therefore does not independently confirm that a phone number is owned or controlled by the user who supplied it. Account confirmation continues through the registered email address.</p></section>
    <section><h2>7. Decklists and user content</h2><p>You retain responsibility for content you submit. Decklists are kept private from other players while a tournament is running, except that tournament admins may access them for event administration. When a tournament is completed, submitted decklists may become visible in that tournament’s public history as part of the service’s record-keeping function.</p></section>
    <section><h2>8. Conduct outside ManaPair</h2><p>ManaPair is not responsible for communications, meetings, matches, travel, purchases, sales, trades, entry fees, prizes, wagers, agreements, misconduct, injuries, losses, or disputes that occur outside the service or between users, tournament organizers, venues, or other third parties. Use your own judgment when interacting with people you meet through a tournament.</p></section>
    <section><h2>9. No warranty</h2><p>ManaPair is provided on an “as is” and “as available” basis. To the maximum extent permitted by applicable law, we do not guarantee uninterrupted availability, error-free operation, permanent storage, accurate third-party card data, or that every tournament result, pairing, or user submission is correct.</p></section>
    <section><h2>10. Limitation of responsibility</h2><p>To the maximum extent permitted by applicable law, ManaPair and its operator will not be liable for indirect, incidental, special, consequential, or punitive damages, or for losses arising from user conduct, tournament administration, prizes, payments, external communications, reliance on submitted results, service outages, or unauthorized activity outside our reasonable control. Nothing in these Terms excludes liability or consumer rights that cannot legally be excluded.</p></section>
    <section><h2>11. Service changes and access</h2><p>We may modify, suspend, restrict, or discontinue features where reasonably necessary for security, maintenance, legal compliance, or operation of the service. We may restrict accounts that abuse the service or create security or safety risks.</p></section>
    <section><h2>12. Privacy</h2><p>Our <Link href="/privacy">Privacy Notice</Link> explains the information used by ManaPair, including how matchup email and phone sharing works.</p></section>
    <p className="legal-note">These Terms are written for ManaPair’s current community/non-commercial use. They should be reviewed by a qualified lawyer if the project becomes commercial, handles payments or prizes, or expands into regulated activity.</p>
  </article>;
}
