-- ManaPair tournament-first schema. Applied to the live Supabase project as roundly_rebuild.
drop view if exists public.player_overall_stats cascade;
drop view if exists public.tournament_standings cascade;
drop function if exists public.start_tournament(uuid) cascade;
drop function if exists public.enforce_tournament_registration() cascade;
drop table if exists public.match_disputes cascade;
drop table if exists public.tournament_matches cascade;
drop table if exists public.tournament_players cascade;
drop table if exists public.matches cascade;
drop table if exists public.decks cascade;
drop table if exists public.tournaments cascade;
drop table if exists public.profiles cascade;

create table public.profiles (user_id uuid primary key references auth.users(id) on delete cascade,display_name text not null check (char_length(display_name) between 2 and 32),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.tournaments (id uuid primary key default gen_random_uuid(),created_by uuid not null references public.profiles(user_id) on delete cascade,name text not null check (char_length(name) between 2 and 80),description text,format text not null default 'Open',mode text not null default 'async' check (mode in ('async','scheduled')),status text not null default 'registration' check (status in ('registration','active','completed')),starts_at timestamptz not null,ends_at timestamptz not null,registration_deadline timestamptz not null,matches_per_player smallint not null default 5 check (matches_per_player between 1 and 20),max_players smallint check (max_players is null or max_players between 2 and 256),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check (ends_at > starts_at),check (registration_deadline <= starts_at));
create table public.tournament_players (tournament_id uuid not null references public.tournaments(id) on delete cascade,user_id uuid not null references public.profiles(user_id) on delete cascade,joined_at timestamptz not null default now(),dropped_at timestamptz,primary key (tournament_id,user_id));
create table public.tournament_matches (id uuid primary key default gen_random_uuid(),tournament_id uuid not null references public.tournaments(id) on delete cascade,player_a uuid not null references public.profiles(user_id) on delete cascade,player_b uuid not null references public.profiles(user_id) on delete cascade,player_a_wins smallint check (player_a_wins between 0 and 2),player_b_wins smallint check (player_b_wins between 0 and 2),status text not null default 'pending' check (status in ('pending','reported')),reported_by uuid references public.profiles(user_id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check (player_a <> player_b),check ((status='pending' and player_a_wins is null and player_b_wins is null) or (status='reported' and player_a_wins is not null and player_b_wins is not null)));
create unique index tournament_matches_unique_pair on public.tournament_matches (tournament_id,least(player_a,player_b),greatest(player_a,player_b));
create table public.match_disputes (id uuid primary key default gen_random_uuid(),match_id uuid not null references public.tournament_matches(id) on delete cascade,raised_by uuid not null references public.profiles(user_id) on delete cascade,reason text,status text not null default 'open' check (status in ('open','resolved')),created_at timestamptz not null default now(),resolved_at timestamptz,resolved_by uuid references public.profiles(user_id) on delete set null);
create unique index one_open_dispute_per_player_match on public.match_disputes(match_id,raised_by) where status='open';
create index tournament_players_user_idx on public.tournament_players(user_id,joined_at desc);create index tournament_matches_tournament_idx on public.tournament_matches(tournament_id,created_at);create index tournament_matches_player_a_idx on public.tournament_matches(player_a,created_at desc);create index tournament_matches_player_b_idx on public.tournament_matches(player_b,created_at desc);create index tournaments_status_start_idx on public.tournaments(status,starts_at);

create or replace function public.enforce_tournament_registration() returns trigger language plpgsql security invoker set search_path=public as $$ declare t public.tournaments%rowtype; current_players integer; begin select * into t from public.tournaments where id=new.tournament_id for update; if not found then raise exception 'Tournament not found.'; end if; if t.status<>'registration' then raise exception 'Registration is closed.'; end if; if now()>t.registration_deadline then raise exception 'The registration deadline has passed.'; end if; if t.max_players is not null then select count(*) into current_players from public.tournament_players where tournament_id=new.tournament_id and dropped_at is null; if current_players>=t.max_players then raise exception 'This tournament is full.'; end if; end if; return new; end; $$;
create trigger tournament_registration_guard before insert on public.tournament_players for each row execute function public.enforce_tournament_registration();

create or replace function public.start_tournament(p_tournament_id uuid) returns integer language plpgsql security invoker set search_path=public as $$ declare t public.tournaments%rowtype; players uuid[]; n integer; k integer; offset_n integer; i integer; j integer; inserted_count integer:=0; begin select * into t from public.tournaments where id=p_tournament_id for update; if not found then raise exception 'Tournament not found.'; end if; if t.created_by<>(select auth.uid()) then raise exception 'Only the tournament admin can start this tournament.'; end if; if t.status<>'registration' then raise exception 'This tournament has already started.'; end if; select array_agg(user_id order by random()) into players from public.tournament_players where tournament_id=p_tournament_id and dropped_at is null; n:=coalesce(array_length(players,1),0); k:=t.matches_per_player; if n<2 then raise exception 'At least two players are required.'; end if; if k>=n then raise exception 'Matches per player must be lower than the number of registered players.'; end if; if mod(n*k,2)=1 then raise exception 'Exact pairings are impossible with % players and % matches per player. players × matches must be even.',n,k; end if; if exists(select 1 from public.tournament_matches where tournament_id=p_tournament_id) then raise exception 'Pairings already exist for this tournament.'; end if; if mod(k,2)=1 then for i in 1..(n/2) loop insert into public.tournament_matches(tournament_id,player_a,player_b) values(p_tournament_id,players[i],players[i+(n/2)]); inserted_count:=inserted_count+1; end loop; end if; for offset_n in 1..(k/2) loop for i in 1..n loop j:=((i-1+offset_n)%n)+1; insert into public.tournament_matches(tournament_id,player_a,player_b) values(p_tournament_id,players[i],players[j]); inserted_count:=inserted_count+1; end loop; end loop; update public.tournaments set status='active',updated_at=now() where id=p_tournament_id; return inserted_count; end; $$;

create view public.tournament_standings with (security_invoker=true) as with score_rows as (select tournament_id,player_a user_id,player_a_wins own_wins,player_b_wins opp_wins from public.tournament_matches where status='reported' union all select tournament_id,player_b,player_b_wins,player_a_wins from public.tournament_matches where status='reported') select tp.tournament_id,tp.user_id,p.display_name,count(sr.user_id)::integer played,count(*) filter(where sr.own_wins>sr.opp_wins)::integer wins,count(*) filter(where sr.own_wins=sr.opp_wins)::integer draws,count(*) filter(where sr.own_wins<sr.opp_wins)::integer losses,(count(*) filter(where sr.own_wins>sr.opp_wins)*3+count(*) filter(where sr.own_wins=sr.opp_wins))::integer points,coalesce(sum(sr.own_wins),0)::integer game_wins,coalesce(sum(sr.opp_wins),0)::integer game_losses,case when count(sr.user_id)=0 then 0::numeric else round((count(*) filter(where sr.own_wins>sr.opp_wins))::numeric*100/count(sr.user_id),1) end win_rate from public.tournament_players tp join public.profiles p on p.user_id=tp.user_id left join score_rows sr on sr.tournament_id=tp.tournament_id and sr.user_id=tp.user_id where tp.dropped_at is null group by tp.tournament_id,tp.user_id,p.display_name;
create view public.player_overall_stats with (security_invoker=true) as with score_rows as (select player_a user_id,player_a_wins own_wins,player_b_wins opp_wins from public.tournament_matches where status='reported' union all select player_b,player_b_wins,player_a_wins from public.tournament_matches where status='reported') select p.user_id,p.display_name,count(sr.user_id)::integer played,count(*) filter(where sr.own_wins>sr.opp_wins)::integer wins,count(*) filter(where sr.own_wins=sr.opp_wins)::integer draws,count(*) filter(where sr.own_wins<sr.opp_wins)::integer losses,case when count(sr.user_id)=0 then 0::numeric else round((count(*) filter(where sr.own_wins>sr.opp_wins))::numeric*100/count(sr.user_id),1) end win_rate from public.profiles p left join score_rows sr on sr.user_id=p.user_id group by p.user_id,p.display_name;

alter table public.profiles enable row level security;alter table public.tournaments enable row level security;alter table public.tournament_players enable row level security;alter table public.tournament_matches enable row level security;alter table public.match_disputes enable row level security;
create policy profiles_public_read on public.profiles for select to anon,authenticated using(true);create policy profiles_insert_self on public.profiles for insert to authenticated with check((select auth.uid())=user_id);create policy profiles_update_self on public.profiles for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
create policy tournaments_public_read on public.tournaments for select to anon,authenticated using(true);create policy tournaments_insert_self on public.tournaments for insert to authenticated with check((select auth.uid())=created_by);create policy tournaments_update_admin on public.tournaments for update to authenticated using((select auth.uid())=created_by) with check((select auth.uid())=created_by);create policy tournaments_delete_admin on public.tournaments for delete to authenticated using((select auth.uid())=created_by);
create policy tournament_players_public_read on public.tournament_players for select to anon,authenticated using(true);create policy tournament_players_join_self on public.tournament_players for insert to authenticated with check((select auth.uid())=user_id);create policy tournament_players_leave_self on public.tournament_players for delete to authenticated using((select auth.uid())=user_id and exists(select 1 from public.tournaments t where t.id=tournament_id and t.status='registration'));create policy tournament_players_admin_delete on public.tournament_players for delete to authenticated using(exists(select 1 from public.tournaments t where t.id=tournament_id and t.created_by=(select auth.uid()) and t.status='registration'));
create policy tournament_matches_public_read on public.tournament_matches for select to anon,authenticated using(true);create policy tournament_matches_admin_insert on public.tournament_matches for insert to authenticated with check(exists(select 1 from public.tournaments t where t.id=tournament_id and t.created_by=(select auth.uid())));create policy tournament_matches_admin_update on public.tournament_matches for update to authenticated using(exists(select 1 from public.tournaments t where t.id=tournament_id and t.created_by=(select auth.uid()))) with check(exists(select 1 from public.tournaments t where t.id=tournament_id and t.created_by=(select auth.uid())));create policy tournament_matches_player_report on public.tournament_matches for update to authenticated using(status='pending' and (select auth.uid()) in(player_a,player_b)) with check(status='reported' and (select auth.uid()) in(player_a,player_b) and reported_by=(select auth.uid()));
create policy disputes_read_relevant on public.match_disputes for select to authenticated using(raised_by=(select auth.uid()) or exists(select 1 from public.tournament_matches m join public.tournaments t on t.id=m.tournament_id where m.id=match_id and (m.player_a=(select auth.uid()) or m.player_b=(select auth.uid()) or t.created_by=(select auth.uid()))));create policy disputes_insert_player on public.match_disputes for insert to authenticated with check(raised_by=(select auth.uid()) and exists(select 1 from public.tournament_matches m where m.id=match_id and m.status='reported' and (m.player_a=(select auth.uid()) or m.player_b=(select auth.uid()))));create policy disputes_update_admin on public.match_disputes for update to authenticated using(exists(select 1 from public.tournament_matches m join public.tournaments t on t.id=m.tournament_id where m.id=match_id and t.created_by=(select auth.uid()))) with check(exists(select 1 from public.tournament_matches m join public.tournaments t on t.id=m.tournament_id where m.id=match_id and t.created_by=(select auth.uid())));
grant usage on schema public to anon,authenticated;grant select on public.profiles,public.tournaments,public.tournament_players,public.tournament_matches to anon,authenticated;grant insert,update on public.profiles to authenticated;grant insert,update,delete on public.tournaments to authenticated;grant insert,delete on public.tournament_players to authenticated;grant insert on public.tournament_matches to authenticated;grant update(player_a_wins,player_b_wins,status,reported_by,updated_at) on public.tournament_matches to authenticated;grant select,insert,update on public.match_disputes to authenticated;grant select on public.tournament_standings,public.player_overall_stats to anon,authenticated;revoke all on function public.start_tournament(uuid) from public;grant execute on function public.start_tournament(uuid) to authenticated;revoke all on function public.enforce_tournament_registration() from public;
